---
- name: Update apt cache
  become: true
  become_user: root
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'
- name: Install git system packages
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - git
      - git-lfs
    state: latest  # noqa package-latest
