---
- name: Converge
  hosts: all
  roles:
    - role: dagos.git
      vars:
        state: present
        git_settings:
          user.name: Max Mustermann
          user.email: max.mustermann@gmx.de
          pull.ff: "false"
