---
- name: Converge
  hosts: all
  vars:
    user_name: max
  pre_tasks:
    - name: Create a test user
      ansible.builtin.user:
        name: "{{ user_name }}"
        state: present
        create_home: true
  roles:
    - role: dagos.git
      become: true
      become_user: "{{ user_name }}"
      vars:
        state: present
        git_settings:
          user.name: Max Mustermann
          user.email: max.mustermann@gmx.de
          pull.ff: "false"
