---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Create a test user
      ansible.builtin.user:
        name: test
        state: present
        create_home: true
  roles:
    - role: dagos.git
      become: true
      become_user: test
      vars:
        state: present
        git_settings:
          user.name: Max Mustermann
          user.email: max.mustermann@gmx.de
          pull.ff: "false"
